version: '3'

# @see
# https://docs.docker.jp/get-started/08_using_compose.html?highlight=mysql#mysql
services:
  database:
    image: mysql:8.0.29
    container_name: mysql-container
    ports:
      - '3006:3306'
    environment:
      MYSQL_DATABASE: company
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf