-- マスタデータ投入
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) values ('無所属'),('営業部'),('企画部'),('開発部'),('人事部');
---- ダミーデータ投入
--INSERT INTO EMPLOYEE (DEPARTMENT_ID, EMPLOYEE_NAME, GENDER) VALUES (1, 'テスト', 'FEMALE');
--INSERT INTO PERSONAL_DATA (EMPLOYEE_ID, BIRTHDAY, TELEPHONE_NUMBER, MAIL_ADDRESS) VALUES (2, '2020-01-01', '00000000000', 'test@gmail.com');
--INSERT INTO HISTORY (START_DATE, EMPLOYEE_ID, DEPARTMENT_ID, CONTENT) VALUES ('2022-01-01', 2, 2, 'テスト入社');
--INSERT INTO HISTORY (START_DATE, EMPLOYEE_ID, DEPARTMENT_ID, CONTENT) VALUES ('2023-01-01', 2, 1, 'テスト退職');