CREATE TABLE DEPARTMENT (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DEPARTMENT_NAME VARCHAR(256) NOT NULL
);

CREATE TABLE EMPLOYEE (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DEPARTMENT_ID BIGINT NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE
);